---
title: "HW2-6"
output:
  html_notebook: default
  html_document: default
---

__Data Loading__
```{r}
spam_train = read.csv("spam.train", header = FALSE)
spam_test = read.csv("spam.test", header = FALSE)
# Shuffle row-wise
set.seed(131)
spam_train = spam_train[sample(nrow(spam_train)),]
spam_test = spam_test[sample(nrow(spam_test)),]

cname = c("word_freq_make","word_freq_address","word_freq_all","word_freq_3d","word_freq_our","word_freq_over","word_freq_remove","word_freq_internet","word_freq_order","word_freq_mail","word_freq_receive","word_freq_will","word_freq_people","word_freq_report","word_freq_addresses","word_freq_free","word_freq_business","word_freq_email","word_freq_you","word_freq_credit","word_freq_your","word_freq_font","word_freq_000","word_freq_money","word_freq_hp","word_freq_hpl","word_freq_george","word_freq_650","word_freq_lab","word_freq_labs","word_freq_telnet","word_freq_857","word_freq_data","word_freq_415","word_freq_85","word_freq_technology","word_freq_1999","word_freq_parts","word_freq_pm","word_freq_direct","word_freq_cs","word_freq_meeting","word_freq_original","word_freq_project","word_freq_re","word_freq_edu","word_freq_table","word_freq_conference","char_freq_;","char_freq_(","char_freq_[","char_freq_!","char_freq_$","char_freq_#","capital_run_length_average","capital_run_length_longest","capital_run_length_total","spam_nonspam")
colnames(spam_train) = cname
colnames(spam_test) = cname
```

__Package Loading__
```{r}
library(gbm)
library(caret)
```

__gbm function calling__
```{r}
set.seed(444) # Random for bag.fraction
gbm0 <- gbm(spam_nonspam~., data = spam_train, train.fraction = 1.0, interaction.depth = 4, shrinkage = .05, n.trees = 2500, bag.fraction = 0.5, cv.folds = 5, distribution = "bernoulli", verbose = T)
```

```{r}
best.iter_train <- gbm.perf(gbm0, method = "cv")
```

__Confusion table of training data__
```{r}
# For training data
gbm0.prediction <- predict(gbm0, spam_train, type ="response", n.trees = best.iter_train)
confusionMatrix(gbm0.prediction > 1/2, spam_train$spam_nonspam == 1)
```

__Confusion table of test data__
```{r}
# For training data
gbm0.prediction <- predict(gbm0, spam_test, type ="response", n.trees = best.iter_train)
confusionMatrix(gbm0.prediction > 1/2, spam_test$spam_nonspam == 1)
```

__Weighted Costs__

```{r}
if(FALSE){
set.seed(444) # Random for bag.fraction

grid <- expand.grid(cost = c(25, 50, 75, 100), depth = c(1, 2, 3, 4, 5, 6), shrinkage = c(0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.040, 0.045, 0.05), minobsinnode = c(5, 10, 15))
grid = grid[sample(nrow(grid)), ]

for(i in 1:nrow(grid)){
  case = tryCatch({
    each_point = grid[i, ]
    f <- function(x){if(x == 0){return(each_point$cost)} else{return(1)}}
    
    gbm1 <- gbm(spam_nonspam~., data = spam_train, train.fraction = 1.0, weights = unlist(Map(f, spam_train$spam_nonspam)), interaction.depth = each_point$depth, shrinkage = each_point$shrinkage, n.minobsinnode = each_point$minobsinnode, n.trees = 4000, bag.fraction = 0.5, cv.folds = 5, distribution = "bernoulli", verbose = T)
    
    best.iter_train <- gbm.perf(gbm1, method = "cv", plot.it = FALSE)
    
    # For training data
    gbm1.prediction <- predict(gbm1, spam_test, type ="response", n.trees = best.iter_train)
    cm <- confusionMatrix(gbm1.prediction > 1/2, spam_test$spam_nonspam == 1)
    #print(cm)
    if(as.list(cm$byClass)$Sensitivity > 0.997){
      print(each_point)
      break
    }
  })
}
}
```

```{r}
f <- function(x){if(x == 0){return(75)} else{return(1)}}
    
gbm1 <- gbm(spam_nonspam~., data = spam_train, train.fraction = 1.0, weights = unlist(Map(f, spam_train$spam_nonspam)), interaction.depth = 1, shrinkage = 0.025, n.minobsinnode = 5, n.trees = 4000, bag.fraction = 0.5, cv.folds = 5, distribution = "bernoulli", verbose = T)
    
best.iter_train <- gbm.perf(gbm1, method = "cv", plot.it = FALSE)
```

__Confusion table of test data__
```{r}
# For training data
gbm1.prediction <- predict(gbm1, spam_test, type ="response", n.trees = best.iter_train)
cm <- confusionMatrix(gbm1.prediction > 1/2, spam_test$spam_nonspam == 1)
cm
```

__Important variables__
```{r}
summary(gbm1, n.tree = best.iter_train, main="RELATIVE INFLUENCE OF ALL PREDICTORS")
```

__The dependence of the response on the most important attributes__
```{r}
names(spam_train)
```

```{r}
plot(gbm1, i.var = 7, n.trees = best.iter_train, main = "Partial Dependence of 'remove'")
```

```{r}
plot(gbm1, i.var = 23, n.trees = best.iter_train, main = "Partial Dependence of '000'")
```

```{r}
plot(gbm1, i.var = 52, n.trees = best.iter_train, main = "Partial Dependence of '!'")
```


```{r}
plot(gbm1, i.var = c(7, 23), n.trees = best.iter_train, main = "Partial Dependence on 'remove' and '000'")
```

```{r}
plot(gbm1, i.var = c(23, 52), n.trees = best.iter_train, main = "Partial Dependence on '000' and '!'")
```

```{r}
plot(gbm1, i.var = c(7, 52), n.trees = best.iter_train, main = "Partial Dependence on 'remove' and '!'")
```